name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install --force
      - run: CI='' npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_PUBLIC_KEY: ${{ secrets.REACT_APP_PUBLIC_KEY }}
          REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }}
          REACT_APP_TEMPLATE_ID: ${{ secrets.REACT_APP_TEMPLATE_ID}}
          AWS_REGION: 'eu-west-3'
          SOURCE_DIR: 'build'